ParnicaV2/ParnicaV2/Models/Litigation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ParnicaV2.Models
{
    public class Litigation
    {
        public  int Id { get; set; }

        [Required]
        public int  LocationId { get; set; }
        public virtual Location Location { get; set; }

        [Required]
        public int JudgeId { get; set; }
        public virtual Contact Judge { get; set; }

        public int? DefendantId { get; set; }
        public virtual Contact Defendant { get; set; }

        public int? ProsecutorId { get; set; }
        public virtual Contact Prosecutor { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        public  DateTime DateAndTime { get; set; }
        public virtual ICollection<ApplicationUser> Lawyers { get; set; }

        [Required]
        public int ProcedureTypeId { get; set; }
        public virtual ProcedureType ProcedureType { get; set; }

        public  string Note { get; set; }

        [Required]
        public  string CourtType { get; set; }

        [Required]
        public  string ProcedureId { get; set; }

        [Required]
        public  int CourtroomNumber { get; set; }

        public Litigation()
        {
            this.Lawyers = new HashSet<ApplicationUser>();
        }
    }
}

ParnicaV2/ParnicaV2/ViewModels/CreateViewModel.cs
using ParnicaV2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ParnicaV2.ViewModels
{
    public class CreateViewModel
    {
        public List<Contact> Kontaki { get; set; }
        public List<Location> Lokacija { get; set; }

        public List<ProcedureType> TipoviPostupka { get; set; }

        //  public List<Kontakt> Tuzioci{ get; set; }
    }
}

ParnicaV2/ParnicaV2/ViewModels/LitigationViewModel.cs
using ParnicaV2.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace ParnicaV2.ViewModels
{
    public class LitigationViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Value cannot be null")]
        [Display(Name = "Location:")]
        public int LocationId { get; set; }

        [Required(ErrorMessage = "Value cannot be null")]
        [Display(Name = "Judge:")]
        public int JudgeId { get; set; }

        [Required(ErrorMessage = "Value cannot be null")]
        [Display(Name = "Defendant:")]
        public int? DefendantId { get; set; }

        [Required(ErrorMessage = "Value cannot be null")]
        [Display(Name = "Prosecutor:")]
        public int? ProsecutorId { get; set; }
   
        [Required(ErrorMessage = "Value cannot be null")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Date and time:")]
        public DateTime DateAndTime { get; set; }

        [Required(ErrorMessage = "Value cannot be null")]
        [Display(Name = "Procedure type:")]
        public int ProcedureTypeId { get; set; }

        [Display(Name = "Note:")]
        public string Note { get; set; }

        [Required(ErrorMessage = "Value cannot be null")]
        [Display(Name = "Court type:")]
        public string CourtType { get; set; }

        [Required(ErrorMessage = "Value cannot be null")]
        [Display(Name = "Procedure ID:")]
        public string ProcedureId { get; set; }

        [Required(ErrorMessage = "Value cannot be null")]
        [Display(Name ="Courtroom number:")]
        public int CourtroomNumber { get; set; }

        public static Litigation FromDTOtoModel(LitigationViewModel p)
        {

            return new Litigation
            {
                Id = p.Id,
                LocationId = p.LocationId,
                JudgeId = p.JudgeId,
                DefendantId = p.DefendantId,
                ProsecutorId = p.ProsecutorId,
                ProcedureId = p.ProcedureId,
                ProcedureTypeId = p.ProcedureTypeId,
                CourtroomNumber = p.CourtroomNumber,
                CourtType = p.CourtType,
                DateAndTime=p.DateAndTime,
                Note=p.Note

            };
        }

        public static LitigationViewModel ToDTO(Litigation p)
        {

            return new LitigationViewModel
            {
                Id = p.Id,
                LocationId = p.LocationId,
                JudgeId = p.JudgeId,
                DefendantId = p.DefendantId,
                ProsecutorId = p.ProsecutorId,
                ProcedureId = p.ProcedureId,
                ProcedureTypeId = p.ProcedureTypeId,
                CourtroomNumber = p.CourtroomNumber,
                CourtType = p.CourtType,
                DateAndTime = p.DateAndTime,
                Note = p.Note

            };

        }
        public static IEnumerable<LitigationViewModel> ToDTOlist(IEnumerable<Litigation> litigations)
        {

            List<LitigationViewModel> l = new List<LitigationViewModel>();
            foreach(var en in litigations)
            {
                l.Add(LitigationViewModel.ToDTO(en));
            }
            return l;

        }
    }
}

ParnicaV2/ParnicaV2/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


using DHTMLX.Scheduler;
using DHTMLX.Common;
using DHTMLX.Scheduler.Data;
using DHTMLX.Scheduler.Controls;

using ParnicaV2.Models;
using ParnicaV2.Services;

namespace ParnicaV2.Controllers
{
    public class CalendarController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            var scheduler = new DHXScheduler(this);
            scheduler.Config.xml_date = "%d/%m/%Y %H:%i";
            scheduler.Config.readonly_form = true;
            scheduler.Lightbox.AddDefaults();
  
            scheduler.InitialDate = DateTime.Now.Date; // new DateTime(2020, 09, 03);

            scheduler.LoadData = true;
            scheduler.EnableDataprocessor = true;

            return View(scheduler);
        }

        [Authorize]
        public ContentResult Data()
        {
            ServiceLitigation service = new ServiceLitigation();
            List<CalendarEvent> listEvants = new List<CalendarEvent>();
            foreach (var parnica in service.List())
            {

                listEvants.Add(new CalendarEvent
                {
                    id = parnica.Id,
                    text = parnica.Id.ToString()
                    + " Location: "+ parnica.Location.Name+
                    " Judge: "+parnica.Judge.Name+
                    " Defendant: "+ parnica.Defendant.Name+
                    " Prosecutor: " + parnica.Prosecutor.Name,

                    start_date = new DateTime(parnica.DateAndTime.Year, parnica.DateAndTime.Month, parnica.DateAndTime.Day, parnica.DateAndTime.Hour,
                    parnica.DateAndTime.Minute, parnica.DateAndTime.Second),

                    end_date = new DateTime(parnica.DateAndTime.Year, parnica.DateAndTime.Month, parnica.DateAndTime.Day, parnica.DateAndTime.Hour+2,
                    parnica.DateAndTime.Minute, parnica.DateAndTime.Second)

                });         
            }

            var data = new SchedulerAjaxData( listEvants );
            return (ContentResult)data;
        }

        [Authorize]
        public ContentResult Save(int? id, FormCollection actionValues)
        {
            var action = new DataAction(actionValues);
            
            try
            {
                var changedEvent = (CalendarEvent)DHXEventsHelper.Bind(typeof(CalendarEvent), actionValues);  

             /*   switch (action.Type)
                {
                    case DataActionTypes.Insert:
                        //do insert
                        //action.TargetId = changedEvent.id;//assign postoperational id
                        break;
                    case DataActionTypes.Delete:
                        //do delete
                        break;
                    default:// "update"                          
                        //do update
                        break;
                }*/
            }
            catch
            {
                action.Type = DataActionTypes.Error;
            }
            return (ContentResult)new AjaxSaveResponse(action);
        }
    }
}

ParnicaV2/ParnicaV2/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using ParnicaV2.Models;
using ParnicaV2.Services;
using ParnicaV2.ViewModels;

namespace ParnicaV2.Controllers
{
    public class ContactsController : Controller
    {
        ServiceContact service = new ServiceContact();

        // GET: Kontakts
        [Authorize(Roles = ("Admin"))]
        public ActionResult Index()
        {         
            
            return View(ContactViewModel.ToDTOlist(service.List()));
        }

        // GET: Kontakts/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact kontakt = service.FindById(id);
            if (kontakt == null)
            {
                return HttpNotFound();
            }
            return View(kontakt);
        }

        [Authorize(Roles = ("Admin"))]
        public ActionResult Create()
        {

            ViewBag.Kompanije = service.ListCompanies();      
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = ("Admin"))]
        public ActionResult Create(ContactViewModel contact)
        {
       
            if (ModelState.IsValid)
            {
                service.Add(ContactViewModel.FromDTOtoModel(contact));             
                return RedirectToAction("Index");
            }
            ViewBag.Kompanije = service.ListCompanies();
            return View(contact);
        }

        [Authorize(Roles = ("Admin"))]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = service.FindById(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            ViewBag.Kompanije = service.ListCompanies();
            return View(ContactViewModel.ToDTO(contact));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = ("Admin"))]
        public ActionResult Edit(ContactViewModel contact)
        {
           
            if (ModelState.IsValid)
            {
                service.Edit(ContactViewModel.FromDTOtoModel(contact));
                return RedirectToAction("Index");
            }
            ViewBag.Kompanije = service.ListCompanies();
            return View(contact);
        }

        [Authorize(Roles = ("Admin"))]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact kontakt = service.FindById(id);
            if (kontakt == null)
            {
                return HttpNotFound();
            }
            return View(kontakt);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = ("Admin"))]
        public ActionResult DeleteConfirmed(int id)
        {
            service.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                service.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ParnicaV2/ParnicaV2/Controllers/LitigationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using ParnicaV2.Models;
using ParnicaV2.Services;
using ParnicaV2.ViewModels;

namespace ParnicaV2.Controllers
{
    public class LitigationsController : Controller
    {

        ServiceLitigation service;

        public LitigationsController()
        {
            service = new ServiceLitigation(); 
        }

        [Authorize]
        public ActionResult Index(string SearchStrLoc,string SearchStrProcType,
          string SearchStrCourtType, string SearchStrJudge)
        {

            SearchStrLoc = String.IsNullOrEmpty(SearchStrLoc) ? "": SearchStrLoc;
            SearchStrProcType = String.IsNullOrEmpty(SearchStrProcType) ? "": SearchStrProcType;
            SearchStrCourtType = String.IsNullOrEmpty(SearchStrCourtType) ? "": SearchStrCourtType;
            SearchStrJudge = String.IsNullOrEmpty(SearchStrJudge) ? "": SearchStrJudge;  

            ViewData["locFilter"] =  SearchStrLoc;
            ViewData["procTypeFilter"] = SearchStrProcType;
            ViewData["courtTypeFilter"] = SearchStrCourtType;
            ViewData["sudijaFilter"] = SearchStrJudge;

            var  parnice = service.List(s => s.ProcedureType.Name.Contains(SearchStrProcType)
                                         && s.Location.Name.Contains(SearchStrLoc)
                                         && s.CourtType.Contains(SearchStrCourtType)
                                         && s.Judge.Name.Contains(SearchStrJudge));

           
            return View(LitigationViewModelList.ToDTOlist(parnice));

        }

        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Litigation parnica = service.GetById(id);
            if (parnica == null)
            {
                return HttpNotFound();
            }
            return View(LitigationViewModelDetails.ToDTO(parnica));
        }

        [Authorize]
        public ActionResult Create()
        {        
            InitViewBagCreate();
            return View();
        }
     

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(LitigationViewModel litigation, string[] advokati)
        {
            if (ModelState.IsValid && advokati!=null)
            {

                service.Add(LitigationViewModel.FromDTOtoModel(litigation), advokati);
   
                return RedirectToAction("Index");
            }
          
            InitViewBagCreate();
            return View(litigation);
        }

        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Litigation litigation = service.GetById(id);
            if (litigation == null)
            {
                return HttpNotFound();
            }

            InitViewBagsEdit(litigation);
          
            return View(LitigationViewModel.ToDTO(litigation));
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(LitigationViewModel litigation, string [] advokati, string[] neadvokati)
        {     
            if (ModelState.IsValid)
            {
                service.Edit(LitigationViewModel.FromDTOtoModel(litigation), advokati, neadvokati);
                return RedirectToAction("Index");
            }
            InitViewBagsEdit(service.GetById(litigation.Id));
            return View(litigation);
        }

        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Litigation parnica = service.GetById(id);
            if (parnica == null)
            {
                return HttpNotFound();
            }
            return View(LitigationViewModelDelete.ToDTO(parnica));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            service.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                service.Dispose();
            }
            base.Dispose(disposing);
        }

        public void InitViewBagsEdit(Litigation l)
        {
            ViewBag.Kontakti = service.ListContacts();
            ViewBag.TipPostupka = service.ListProcedureTypes();
            ViewBag.Lokacije = service.ListLocations();
            ViewBag.Advokati = UserViewModelForLitigation.toDTOList(l.Lawyers);
            var neAdv = service.ListUsers().Where(x => !l.Lawyers.Contains(x));
            ViewBag.NeAdvokati = UserViewModelForLitigation.toDTOList(neAdv);
        }
        public void InitViewBagCreate()
        {
            ViewBag.Kontakti = service.ListContacts();
            ViewBag.TipPostupka = service.ListProcedureTypes();
            ViewBag.Lokacije = service.ListLocations();
            ViewBag.Korisnici = UserViewModelForLitigation.toDTOList(service.ListUsers());
        }
    }
}

ParnicaV2/ParnicaV2/Views/Litigations/Create.cshtml
@model ParnicaV2.ViewModels.LitigationViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Litigation</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.DateAndTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateAndTime, new { htmlAttributes = new { type = "datetime-local" } })
            @Html.ValidationMessageFor(model => model.DateAndTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CourtType, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @{
                Dictionary<string, string> d = new Dictionary<string, string>();
                d.Add("District", "District");
                d.Add("Family Violence", "Family Violence");
                d.Add("High", "High");
                d.Add("Appeal", "Appeal");
                d.Add("Coroners", "Coroners");
               

                @Html.DropDownListFor(model => model.CourtType, new SelectList(d,"Key", "Value"), htmlAttributes: new { @class = "form-control" });
               @Html.ValidationMessageFor(model => model.CourtType, "", new { @class = "text-danger" });
            }
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProcedureId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProcedureId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProcedureId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CourtroomNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CourtroomNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CourtroomNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LocationId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.ListBoxFor(model => model.LocationId, new SelectList(ViewBag.Lokacije, "Id", "Name"),htmlAttributes:new  { @class="form-control" })
            @Html.ValidationMessageFor(model => model.LocationId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.JudgeId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.ListBoxFor(model => model.JudgeId, new SelectList(ViewBag.Kontakti, "Id", "Name"),htmlAttributes:new  { @class="form-control" })
            @Html.ValidationMessageFor(model => model.JudgeId, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ProcedureTypeId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.ListBoxFor(model => model.ProcedureTypeId, new SelectList(ViewBag.TipPostupka, "Id", "Name"),htmlAttributes:new  { @class="form-control" })
            @Html.ValidationMessageFor(model => model.ProcedureTypeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DefendantId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.ListBoxFor(model => model.DefendantId, new SelectList(ViewBag.Kontakti, "Id", "Name"), htmlAttributes:new  { @class="form-control" })
            @Html.ValidationMessageFor(model => model.DefendantId, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ProsecutorId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.ListBoxFor(model => model.ProsecutorId, new SelectList(ViewBag.Kontakti, "Id", "Name"), htmlAttributes:new  { @class="form-control" })
            @Html.ValidationMessageFor(model => model.ProsecutorId, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group">
        @Html.Label("Lawyers", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.ListBox("Advokati", new MultiSelectList(ViewBag.Korisnici, "Id", "FullName"), htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ParnicaV2/ParnicaV2/Views/Litigations/Details.cshtml
@model ParnicaV2.ViewModels.LitigationViewModelDetails

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Litigation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateAndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourtType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourtType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProcedureId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProcedureId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourtroomNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourtroomNumber)

        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Defendant)

        </dt>

        <dd>
            @Html.DisplayFor(model => model.Defendant.FullName) |
            @Html.ActionLink("Details", "Details", "Contacts", new { id = Model.Defendant.Id },null)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Prosecutor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prosecutor.FullName)  |
            @Html.ActionLink("Details", "Details", "Contacts", new { id = Model.Prosecutor.Id }, null)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Judge)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Judge.FullName) |
            @Html.ActionLink("Details", "Details", "Contacts", new { id = Model.Judge.Id }, null)

        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProcedureType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProcedureType)
        </dd>
    </dl>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Zaduzeni advokati")
            </th>
          
        </tr>
        @foreach (var item in Model.Lawyers)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details","ApplicationUsers", new { id = item.Id },null) 
             
                 </td>
               
            </tr>
        }
    </table>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) 
    @Html.ActionLink("Back to List", "Index")
</p>

ParnicaV2/ParnicaV2/Views/Litigations/Index.cshtml
@model IEnumerable<ParnicaV2.ViewModels.LitigationViewModelList>

@{
    ViewBag.Title = "Index";

}

<h2>Litigations</h2>

<p>
    @Html.ActionLink("Calendar view", "Index", "Calendar",null, new { @class= "btn btn-default"})
    @Html.ActionLink("Create New", "Create",null, new { @class= "btn btn-default"})
</p>

@using (Html.BeginForm("Index", "Litigations", FormMethod.Get))
{
    <div class="form-actions">
        
        <div class="form-horizontal">
            <div class="form-group">
                <div class="col-md-10">
                    Location: @Html.TextBox("SearchStrLoc", ViewData["locFilter"])
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    Procedure type:  @Html.TextBox("SearchStrProcType", ViewData["procTypeFilter"])
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    Court type:  @Html.TextBox("SearchStrCourtType", ViewData["courtTypeFilter"])
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    Judge: @Html.TextBox("SearchStrJudge", ViewData["judgeFilter"])
                </div>
            </div>         
            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" value="Search" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
   


}
<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.DateAndTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Note)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CourtType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProcedureId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CourtroomNumber)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DateAndTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Note)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourtType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProcedureId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourtroomNumber)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>